HouseholdBudgeter/Models/CodeFirst/Households.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HouseholdBudgeter.Models
{
    public class Households
    {
        public Households()
        {
            this.User = new HashSet<ApplicationUser>();
            this.FinancialAccount = new HashSet<FinancialAccounts>();
            this.Invitation = new HashSet<Invitations>();
            this.Budget = new HashSet<Budgets>();
            this.Category = new HashSet<Categories>();
        }
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }

        public virtual ICollection<Budgets> Budget { get; set; }
        public virtual ICollection<ApplicationUser> User { get; set; }
        public virtual ICollection<FinancialAccounts> FinancialAccount { get; set; }
        public virtual ICollection<Invitations> Invitation { get; set; }
        public virtual ICollection<Categories> Category { get; set; }


    }
}

HouseholdBudgeter/Controllers/FinancialAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HouseholdBudgeter.Models;
using Microsoft.AspNet.Identity;

namespace HouseholdBudgeter.Controllers
{
    public class FinancialAccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FinancialAccounts
        [Authorize]
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var userhouseholdid = user.HouseholdId;
            var financialAccount = db.FinancialAccount.Where(f => f.Household.Id == userhouseholdid && f.Active == true);

            return View(financialAccount.ToList());

        }

        // GET: FinancialAccounts/Details/5
        public PartialViewResult _AcctDetails(int? id)
        {
            if (id == null)
            {
                return PartialView(HttpStatusCode.BadRequest);
            }
            var user = db.Users.Find(User.Identity.GetUserId());
            FinancialAccounts financialAccounts = db.FinancialAccount.Find(id);
            var userhousehold = db.Users.Find(User.Identity.GetUserId()).Household;
            
            var incomeItems = financialAccounts.Transaction.Where(t => t.Category.Expense == false && t.Active == true);
            var expenseItems = financialAccounts.Transaction.Where(t => t.Category.Expense == true && t.Active == true);
            var totalRecexp = expenseItems.Where(t => t.Reconciled == true && t.Category.Expense == true).Sum(t => t.Amount);
            var totalRecInc = incomeItems.Where(t => t.Reconciled == true && t.Category.Expense == false).Sum(t => t.Amount);
            var budgetexptotal = userhousehold.Budget.Where(b => b.HouseholdId == userhousehold.Id).Where(b => b.Category.Expense == true).Sum(b => b.Amount);
            var budgetinctotal = userhousehold.Budget.Where(b => b.HouseholdId == userhousehold.Id).Where(b => b.Category.Expense == false).Sum(b => b.Amount);
            var transactions = userhousehold.FinancialAccount.SelectMany(item => item.Transaction).ToList();
            var expense = transactions.Where(t => t.Category.Expense == true && t.Active == true);
            var exptotal = expense.Where(item => item.Reconciled == true).Sum(item => item.Amount);
            ViewBag.totalAmt = incomeItems.Sum(t => t.Amount) - expenseItems.Sum(t => t.Amount);
            ViewBag.recAmount = totalRecInc - totalRecexp;
            ViewBag.budgetTotal = budgetexptotal - budgetinctotal;
            ViewBag.remBud = budgetexptotal - budgetinctotal - exptotal;
            ViewBag.incTotal = incomeItems.Sum(t => t.Amount);
            ViewBag.expTotal = expenseItems.Sum(t => t.Amount);

            if (financialAccounts == null)
            {
                return PartialView(userhousehold);
            }

            return PartialView(financialAccounts);
        }

        // GET: FinancialAccounts/Create
        public ActionResult Create()
        {
            ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name");
            return View();
        }

        // POST: FinancialAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Balance,HouseholdId")] FinancialAccounts financialAccounts)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());
                var household = user.Household;

                if(household == null)
                {
                    TempData["householdId"] = "Please first create or join a household";

                    return RedirectToAction("CreateJoinHousehold", "Households");
                }
                financialAccounts.Created = System.DateTimeOffset.Now;
                financialAccounts.HouseholdId = household.Id;
                financialAccounts.Active = true;
                db.FinancialAccount.Add(financialAccounts);
                db.SaveChanges();

                if(financialAccounts.Balance != 0)
                {
                    Transactions transaction = new Transactions();
                    transaction.Active = true;
                    transaction.Amount = financialAccounts.Balance;
                    transaction.CategoryId = 4;
                    transaction.Created = System.DateTimeOffset.Now;
                    transaction.Description = "Initial Balance";
                    transaction.FinancialAccountId = financialAccounts.Id;
                    transaction.LastUpdatedUserId = user.Id;
                    transaction.Reconciled = true;
                    transaction.TransactionDate = System.DateTimeOffset.Now;
                    transaction.TransactionUserId = user.Id;
                    db.Transaction.Add(transaction);
                    db.SaveChanges();
                }

                var householdaccount = user.Household.FinancialAccount.Where(h => h.Id == financialAccounts.Id);
                var attachaccount = db.FinancialAccount.Where(a => a.Id == financialAccounts.Id);
                householdaccount = attachaccount;
                db.SaveChanges();

                return RedirectToAction("Index", "Households", new { id = financialAccounts.Id});
            }

            ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name", financialAccounts.HouseholdId);
            return View(financialAccounts);
        }

        // GET: FinancialAccounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FinancialAccounts financialAccounts = db.FinancialAccount.Find(id);
            if (financialAccounts == null)
            {
                return HttpNotFound();
            }
            ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name", financialAccounts.HouseholdId);
            return View(financialAccounts);
        }

        // POST: FinancialAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Balance,HouseholdId,Created,Updated,LastReconciledDate")] FinancialAccounts financialAccounts)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());
                var household = user.Household;
                financialAccounts.HouseholdId = household.Id;
                financialAccounts.Updated = System.DateTimeOffset.Now;
                financialAccounts.Active = true;
                db.Entry(financialAccounts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Households", new { id = financialAccounts.Id });
            }
            ViewBag.HouseholdId = new SelectList(db.Household, "Id", "Name", financialAccounts.HouseholdId);
            return RedirectToAction("Index", "Households", new { id = financialAccounts.Id });
        }

        // GET: FinancialAccounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FinancialAccounts financialAccounts = db.FinancialAccount.Find(id);
            if (financialAccounts == null)
            {
                return HttpNotFound();
            }
            return View(financialAccounts);
        }

        // POST: FinancialAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FinancialAccounts financialAccounts = db.FinancialAccount.Find(id);
            financialAccounts.Active = false;
            db.Entry(financialAccounts).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", "Households");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HouseholdBudgeter/Views/Households/CreateJoinHousehold.cshtml
@model HouseholdBudgeter.Models.Households

@{
    ViewBag.Title = "Create or Join";
    Layout = "~/Views/Shared/_CJLayout.cshtml";
}

@Html.HiddenFor(model => model.Created)
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <center>
                <h4>Create</h4>
            </center>
        </div>
        <div class="panel-body">
            <center>
                <br />

                @using (Html.BeginForm("Create", "Households", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div>
                                <input type="text" name="Name" placeholder="Enter Household Name" required />
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div>
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </center>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <center>
                <h4>Join</h4>
            </center>
        </div>
        <div class="panel-body">
            <center>
                <br />
                @if (ViewBag.HouseholdInv != null)
                {
                    using (Html.BeginForm("Join", "Households", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                                    <p>Currently you have an invitation from </p>
                            <br />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.DropDownList("HouseholdInv", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <br />
                        <div class="form-group">
                            <div>
                                <input type="submit" value="Join" class="btn btn-default" />
                            </div>
                        </div>
                    }
                }
                else
                {
                    <p>Currently you have no invitation from any household</p>
                }
            </center>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <center>
                <h4>Rejoin</h4>
                </center>
            </div>
        <div class="panel-body">
            <center>
                <br />
                @if (@ViewBag.HouseholdArchive != null)
                {
                    using (Html.BeginForm("Archive", "Households", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <p>Choose an archived household</p>
                            <br />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.DropDownList("HouseholdArchive", null, htmlAttributes: new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <br />
                        <div class="form-group">
                            <div>
                                <input type="submit" value="Rejoin" class="btn btn-default" />
                            </div>
                        </div>
                    }
                }
                else
                {
                    <p>Currently you have no archived household</p>
                }

            </center>
        </div>
    </div>
</div>

HouseholdBudgeter/Views/Households/Delete.cshtml
@model HouseholdBudgeter.Models.Households

@{
    ViewBag.Title = "Leave";
    Layout = null;
}


<div class="bootbox modal fade bootbox-prompt in" tabindex="-1" role="dialog" aria-hidden="false" style="display: block; padding-right: 17px;">

    <div class="modal-backdrop fade in" data-dismiss="modal">
    </div>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"><i class="fa fa-external-link red"></i>&nbsp;&nbsp;&nbsp;Leave</h4>
                </div>
                <div class="modal-body">
                    <div class="bootbox-body">

                        <h4>Are you sure you want to leave this household?</h4>
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Name)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Name)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Created)
                                </dt>

                                <dd>
                                    @Model.Created.ToString("d")
                                </dd>
                                <dt>
                                    Members
                                </dt>
                                @foreach (var user in Model.User)
                                {


                                    <dd>
                                        @Html.DisplayFor(model => user.FirstName)
                                        @Html.DisplayFor(model => user.LastName)
                                    </dd>
                                }

                            </dl>
                        </div>
                    </div>
                <div class="modal-footer">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
                    <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
                    <button data-bb-handler="confirm" type="submit" class="btn btn-primary">Leave</button>
}
                </div>
            </div>
        </div>
</div>

HouseholdBudgeter/Views/Households/Details.cshtml
@model HouseholdBudgeter.Models.Households

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-xs-12">
        <div class="row">
            <div class="col-sm-6">
                <div class="tabbable">
                    <ul class="nav nav-tabs" id="myTab">
                        <li class="active">
                            <a data-toggle="tab" href="#home">
                                <i class="green ace-icon fa fa-home bigger-120"></i>
                                Household
                            </a>
                        </li>
                        
                        <li>
                            <a data-toggle="tab" href="#messages">
                                Messages
                                <span class="badge badge-danger">4</span>
                            </a>
                        </li>

                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                Accounts &nbsp;
                                <i class="ace-icon fa fa-caret-down bigger-110 width-auto"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-info">
                                @foreach (var item in Model.FinancialAccount)
                                {
                                    <li>
                                        <a href="@Url.Action("Details","FinancialAccounts", new { id = item.Id })">@Html.DisplayFor(modelItem => item.Name)</a>
                                    </li>
                                }
                                
                                <li>
                                    <a href="@Url.Action("Create","FinancialAccounts")">Add new account</a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div id="home" class="tab-pane fade in active">
                            @if (Model.Name != null)
                            {
                                <h4>
                                    @Html.DisplayFor(model => model.Name)


                                    <a href="@Url.Action("Edit", "Households", new { id = Model.Id })" title="Edit Household Name" data-original-title="Edit Household Name">
                                        <div class="ui-pg-div" style="display:inline" align="right">
                                            <span class="ui-icon ace-icon fa fa-pencil blue">
                                            </span>
                                        </div>
                                    </a>

                                    <a href="@Url.Action("Delete", "Households", new { id = Model.Id })" title="Leave this Household" data-original-title="Leave this Household">
                                        <div class="ui-pg-div" style="display:inline" align="right">
                                            <span class="ui-icon ace-icon fa fa-trash-o red">
                                            </span>
                                        </div>
                                    </a>
                                </h4>
                            }
                            else
                            {
                                <text>First create or join a household</text>
                            }

                            <hr />
                            @if (Model.Name != null)
                            {
                                <dl class="dl-horizontal">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.Created)
                                    </dt>

                                    <dd>
                                        @Model.Created.ToString("d")
                                    </dd>
                                    <dt>
                                        Members
                                    </dt>
                                    @foreach (var user in Model.User)
                                    {


                                        <dd>
                                            @Html.DisplayFor(model => user.FirstName)
                                            @Html.DisplayFor(model => user.LastName)
                                        </dd>
                                    }

                                    <dd>
                                        @Html.ActionLink("Invite more members", "Invite", "Households")
                                    </dd>

                                    <dt>
                                        @Html.ActionLink("Bank Accounts", "Index", "FinancialAccounts")
                                    </dt>

                                </dl>
                            }
                            else
                            {
                                <div class="col-md-offset-2 col-md-10">
                                    <a href="@Url.Action("CreateJoinHousehold","Households")" class="btn btn-default">Create or Join</a>
                                </div>
                            }
                        </div>

                        <div id="messages" class="tab-pane fade">
                            <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.</p>
                        </div>

                        <div id="dropdown1" class="tab-pane fade">
                            <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
                        </div>

                        <div id="dropdown2" class="tab-pane fade">
                            <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin.</p>
                        </div>
                    </div>
                </div>
            </div><!-- /.col -->
            <div class="vspace-6-sm"></div>
        </div>
    </div>
</div>

HouseholdBudgeter/Views/Households/Edit.cshtml
@model HouseholdBudgeter.Models.Households

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<div class="bootbox modal fade bootbox-prompt in" tabindex="-1" role="dialog" aria-hidden="false" style="display: block; padding-right: 17px;">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="modal-backdrop fade in" data-dismiss="modal">
    </div>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"><i class="fa fa-pencil blue"></i>&nbsp;&nbsp;&nbsp;Edit Household Name</h4>
                </div>
                <div class="modal-body">
                    <div class="bootbox-body">
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
                        <button data-bb-handler="confirm" type="submit" class="btn btn-primary">Save</button>
                    </div>
            </div>
        </div>
</div>
}
</div>

HouseholdBudgeter/Views/Households/Invite.cshtml
@model HouseholdBudgeter.Models.Invitations
@{
    ViewBag.Title = "Invite";
    Layout = null;
}


<div class="bootbox modal fade bootbox-prompt in" tabindex="-1" role="dialog" aria-hidden="false" style="display: block; padding-right: 17px;">
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.HouseholdId)
    <div class="modal-backdrop fade in" data-dismiss="modal">
    </div>
    @using (Html.BeginForm("Invite", "Households", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"><i class="fa fa-users green"></i>&nbsp;&nbsp;&nbsp;Invite</h4>
        </div>
        <div class="modal-body">
        <div class="bootbox-body">

            @Html.AntiForgeryToken()

            @Html.ValidationSummary("", new { @class = "text-danger" })
            <label class="block clearfix" style="width:500px">
                <span class="block input-icon input-icon-right">
                    @Html.TextBoxFor(m => m.InviteName, new { @class = "form-control", placeholder = "Enter Name", @required = "required" })
                    <i class="ace-icon fa fa-user"></i>
                </span>
            </label>
            <label class="block clearfix" style="width:500px">
                <span class="block input-icon input-icon-right">
                    @Html.TextBoxFor(m => m.InviteEmail, new { @class = "form-control", placeholder = "Enter Email", @required = "required", type = "email" })
                    <i class="ace-icon fa fa-envelope"></i>
                </span>
            </label>
            </div>
        </div>
        <div class="modal-footer">
        <button data-dismiss ="modal" type="button" class="btn btn-default">Cancel</button>
        <button data-bb-handler="confirm" type="submit" class="btn btn-primary">Send</button>
        </div>
        </div>
    </div>
    }
</div>