HouseholdBudgeter/Models/CodeFirst/Budgets.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HouseholdBudgeter.Models
{
    public class Budgets
    {
        public int Id { get; set; }
        public int HouseholdId { get; set; }
        [Required]
        public bool Expense { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:F2}", ApplyFormatInEditMode = true)]
        public decimal Amount { get; set; }
        [Required]
        public int Frequency { get; set; }
        public string AuthorUserId { get; set; }
        public string UpdatedLastUserId { get; set; }

        public virtual Households Household { get; set; }
        public virtual Categories Category { get; set; }
        public virtual ApplicationUser AuthorUser { get; set; }
        public virtual ApplicationUser UpdatedlastUser { get; set; }
        
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }
    }
}

HouseholdBudgeter/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HouseholdBudgeter.Models;
using Microsoft.AspNet.Identity;

namespace HouseholdBudgeter.Controllers
{
    public class BudgetsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Budgets
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            Households household = user.Household;
            var budget = household.Budget;
            return View(budget.ToList());
        }

        // GET: Budgets/Details/5
        public PartialViewResult _BudDetails(int? id)
        {
            if (id == null)
            {
                return PartialView(HttpStatusCode.BadRequest);
            }
            Budgets budgets = db.Budget.Find(id);

            if (budgets == null)
            {
                return PartialView ("Index","Households");
            }
            return PartialView(budgets);
        }

        // GET: Budgets/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Category.OrderBy(c => c.Expense), "Id", "Name");
            return View();
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryId,Description,Amount")] Budgets budgets)
        {
            

            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());
                var household = user.Household;

                budgets.HouseholdId = household.Id;
                budgets.Household = household;
                budgets.AuthorUserId = user.Id;
                budgets.AuthorUser = user;
                budgets.UpdatedLastUserId = user.Id;
                budgets.UpdatedlastUser = user;
                budgets.Created = System.DateTimeOffset.Now;
                db.Budget.Add(budgets);
                db.SaveChanges();
                return RedirectToAction("Index", "Households");
            }

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", budgets.CategoryId);
            return RedirectToAction("Index", "Households");
        }

        // GET: Budgets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budgets budget = db.Budget.Find(id);

            if (budget == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", budget.CategoryId);
            return View(budget);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Created,CategoryId,Description,Amount")] Budgets budgets)
        {
            
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());
                var household = user.Household;
                budgets.HouseholdId = household.Id;
                budgets.UpdatedLastUserId = user.Id;
                budgets.Updated = System.DateTimeOffset.Now;
                db.Entry(budgets).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Households");
            }

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", budgets.CategoryId);

            return RedirectToAction("Index", "Households");
        }

        // GET: Budgets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budgets budgets = db.Budget.Find(id);
            if (budgets == null)
            {
                return HttpNotFound();
            }
            return View(budgets);
        }

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Budgets budgets = db.Budget.Find(id);
            db.Budget.Remove(budgets);
            db.SaveChanges();
            return RedirectToAction("Index", "Households");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HouseholdBudgeter/Views/Budgets/Create.cshtml
@model HouseholdBudgeter.Models.Budgets

@{
    ViewBag.Title = "Create";
    Layout = null;
}

<div class="bootbox modal fade bootbox-prompt in" tabindex="-1" role="dialog" aria-hidden="false" style="display: block; padding-right: 17px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.HouseholdId);
        @Html.HiddenFor(model => model.Created);

        <div class="modal-backdrop fade in" data-dismiss="modal">
        </div>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"><i class="fa fa-plus-circle blue"></i>&nbsp;&nbsp;&nbsp;Create Budget</h4>
                </div>
                <div class="modal-body">
                    <div class="bootbox-body">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder="Enter Description", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", placeholder="Enter Amount", @required = "required", type = "decimal" } })
                                    @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
                        <button data-bb-handler="confirm" type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

HouseholdBudgeter/Views/Budgets/Delete.cshtml
@model HouseholdBudgeter.Models.Budgets

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

@Html.HiddenFor(model => model.Id)
<div class="bootbox modal fade bootbox-prompt in" tabindex="-1" role="dialog" aria-hidden="false" style="display: block; padding-right: 17px;">
    <div class="modal-backdrop fade in" data-dismiss="modal">
    </div>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><i class="fa fa-trash-o red"></i>&nbsp;&nbsp;&nbsp;Delete Budget</h4>
            </div>
            <div class="modal-body">
                <div class="bootbox-body">

                    <h4>Are you sure you want to delete this?</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Category.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Category.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Description)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Amount)
                        </dt>

                        <dd>
                            $@Html.DisplayFor(model => model.Amount)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Created)
                        </dt>

                        <dd>
                            @Model.Created.ToString("d")
                        </dd>
                        @if (Model.Updated != null)
                        {
                            <dt>
                                @Html.DisplayNameFor(model => model.Updated)
                            </dt>

                            <dd>
                                @Model.Updated.Value.ToString("d")
                            </dd>
                        }
                        

                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
                        <button data-bb-handler="confirm" type="submit" class="btn btn-primary">Delete</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

HouseholdBudgeter/Views/Budgets/Edit.cshtml
@model HouseholdBudgeter.Models.Budgets

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<div class="bootbox modal fade bootbox-prompt in" tabindex="-1" role="dialog" aria-hidden="false" style="display: block; padding-right: 17px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Created)
        @Html.HiddenFor(model => model.Updated)
        @Html.HiddenFor(model => model.UpdatedLastUserId)

        <div class="modal-backdrop fade in" data-dismiss="modal">
        </div>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"><i class="fa fa-pencil blue"></i>&nbsp;&nbsp;&nbsp;Edit Account Name</h4>
                </div>
                <div class="modal-body">
                    <div class="bootbox-body">
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @required = "required", type = "decimal" } })
                                    @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
                        <button data-bb-handler="confirm" type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

HouseholdBudgeter/Views/Budgets/Index.cshtml
@model IEnumerable<HouseholdBudgeter.Models.Budgets>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Custom.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Household.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedlastUser.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Expense)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Frequency)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Updated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AuthorUser.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Household.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedlastUser.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Expense)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Frequency)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Updated)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}
</table>


@section Scripts {
    <script>
    $(document).ready(function () {
        $("#accdetails-partial").load('/FinancialAccounts/_AcctDetails/' + @ViewBag.AcctId);
    })
    </script>
    <script>
    $(".AcctDetails").click(function () {
        $("#accdetails-partial").load('/FinancialAccounts/_AcctDetails/' + $(this).data('id'));
    })
    </script>
    <script>
    $(document).on("click", ".TransDetails", function () {
        $("#transdetails-partial").load('/Transactions/_TransDetails/' + $(this).data('id'));
    })
    </script>
}

HouseholdBudgeter/Views/Budgets/_BudDetails.cshtml
@model HouseholdBudgeter.Models.Budgets

@{
    ViewBag.Title = "Details";
    Layout = null;
}


<div class="col-sm-12" style="padding-left:0px; padding-right:0px">
    <div class="widget-box">
        <div class="widget-header" align="center">
            <h5 class="widget-title lighter smaller">
                <i class="ui-icon ace-icon fa fa-edit blue"></i>
                @Html.DisplayFor(model => model.Description)
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="@Url.Action("Edit", "Budgets", new { id = Model.Id })" data-target="#budeditModal" data-toggle="modal" title="Edit Account">
                    <div class="ui-pg-div" style="display:inline">
                        <span class="ui-icon ace-icon fa fa-pencil blue">
                        </span>
                    </div>
                </a>

                <a href="@Url.Action("Delete", "Budgets", new { id = Model.Id })" data-target="#buddeleteModal" data-toggle="modal" title="Delete Account" data-original-title="Delete Account">
                    <div class="ui-pg-div" style="display:inline">
                        <span class="ui-icon ace-icon fa fa-trash-o red">
                        </span>
                    </div>
                </a>
            </h5>
        </div>

        <div class="widget-body">
            <div class="widget-main no-padding">
                <div class="dialogs">
                    <div class="itemdiv dialogdiv">
                        <dl class="dl-horizontal">

                            <dt>
                                @Html.DisplayNameFor(model => model.Amount)
                            </dt>

                            <dd>
                                $@Html.DisplayFor(model => model.Amount)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Created)
                            </dt>

                            <dd>
                                @Model.Created.ToString("d")
                            </dd>

                            @if (Model.Updated != null)
                            {
                                <dt>
                                    @Html.DisplayNameFor(model => model.Updated)
                                </dt>

                                <dd>
                                    @Model.Updated.Value.ToString("d")
                                </dd>
                            }

                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        